pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }


}
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.4.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }


}
rootProject.name = "OD_LEARN"
include ':app'
include ':lib'
include ':startup'
include ':opengl'
include ':tab'
include ':noHttp'
include ':composeView'
//include ':mvi-base'
include ':architecture'
include ':guide'
include ':lib_websocket'
include ':weitong'
